name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: docker build -t your-dockerhub-username/your-image-name .

    # Step 4: Push Image to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Image to Docker Hub
      run: docker push your-dockerhub-username/your-image-name

    # Step 5: Deploy to EC2
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull your-dockerhub-username/your-image-name
          docker stop current-container || true
          docker rm current-container || true
          docker run -d --name current-container -p 80:80 your-dockerhub-username/your-image-name
